name: Microservice Continuous Integration

on:
  workflow_call:
    inputs:
      dotnet-version:
        type: string
        required: true
      warnings-as-errors:
        type: boolean
        required: false
        default: false
      unit-tests-project:
        type: string
        required: false
        default: ''
      integration-tests-project:
        type: string
        required: false
        default: ''
      artifact-name:
        type: string
        required: false
        default: build-artifacts
      release-prefix:
        type: string
        required: false
        default: ${{ github.repository }}
      main-project:
        type: string
        required: true
      dockerfile:
        type: string
        required: false
      image-name:
        type: string
        required: false
        default: ${{ github.repository }}
      docker-username:
        type: string
        required: false
        default: ${{ github.repository_owner }}
      registry-url:
        type: string
        required: false
        default: ghcr.io
    secrets:
      docker-password:
        required: false
    outputs:
      version:
        value: ${{ jobs.build.outputs.version }}
      released:
        value: ${{ jobs.release.outputs.released == 'true' }}

jobs:
  build:
    name: Build Microservice
    uses: ./.github/workflows/build.yml
    with:
      dotnet-version: ${{ inputs.dotnet-version }}
      warnings-as-errors: ${{ inputs.warnings-as-errors }}
      unit-tests-project: ${{ inputs.unit-tests-project }}
      integration-tests-project: ${{ inputs.integration-tests-project }}
      artifact-name: ${{ inputs.artifact-name }}
      projects: ${{ inputs.main-project }}

  docker-build:
    name: Build Docker Images
    needs: [build]
    if: ${{ inputs.dockerfile != '' }}
    uses: ./.github/workflows/docker-delivery.yml
    with:
      dockerfile: ${{ inputs.dockerfile }}
      image-name: ${{ inputs.image-name }}
      docker-username: ${{ inputs.docker-username }}
      registry-url: ${{ inputs.registry-url }}
    secrets:
      docker-password: ${{ secrets.docker-password }}

  release:
    name: GitHub Release
    needs: [build]
    if: needs.build.outputs.should-release == 'true'
    uses: ./.github/workflows/github-delivery.yml
    with:
      version: ${{ needs.build.outputs.version }}
      is-prerelease: ${{ needs.build.outputs.is-prerelease }}
      release-prefix: ${{ inputs.release-prefix }}
